### ISSUE TITLE
parrallel decoding are even slower

### ISSUE THREAD

**Issue by hasuoshenyun** [teelinsan/parallel-decoding#2]
I run the source code both on GPU (A100) and CPU, but I got the result like below.
It's even slower with the proposed algorithms.
My device info:

CPU
processor	: 124
vendor_id	: GenuineIntel
cpu family	: 6
model		: 106
model name	: Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz
stepping	: 6
microcode	: 0xd0003b9
cpu MHz		: 799.967
cache size	: 49152 KB
physical id	: 1
siblings	: 64
core id		: 28
cpu cores	: 32

Test Info
+----------------------------+-----------+----------+------------------+-------------+-------------+
| Model                      | Dataset   | Device   | Best Algorithm   |   Sentences | Languages   |
+============================+===========+==========+==================+=============+=============+
| Helsinki-NLP/opus-mt-en-ro | wmt16     | cuda     | a                |        1999 | en-ro       |
+----------------------------+-----------+----------+------------------+-------------+-------------+

Benchmark
=========  ================  =========  ===========  ===============  ===================
Metrics      autoregressive     jacobi    gs_jacobi    hybrid_jacobi  beam_search
=========  ================  =========  ===========  ===============  ===================
Speedup T          1          0.668        0.81             0.799     0.585
Speedup I          1          1.018        1.046            1.046     na
Time               0.107718   0.161182     0.132987         0.134801  0.18416732640703115
Iter              31.1886    30.6323      29.8164          29.8279    0.0
=========  ================  =========  ===========  ===============  ===================

Bleu
==========  ====================================  ====================================  ====================================  ====================================  ====================================
Metrics     autoregressive                        jacobi                                gs_jacobi                             hybrid_jacobi                         beam_search
==========  ====================================  ====================================  ====================================  ====================================  ====================================
Score       27.419231268671602                    27.419298033635986                    27.419298033635986                    27.419298033635986                    27.755399068985827
Counts      [28468, 15781, 9514, 5853]            [28468, 15781, 9514, 5853]            [28468, 15781, 9514, 5853]            [28468, 15781, 9514, 5853]            [28648, 15920, 9682, 5999]
Totals      [48490, 46491, 44494, 42500]          [48488, 46489, 44492, 42498]          [48488, 46489, 44492, 42498]          [48488, 46489, 44492, 42498]          [49015, 47016, 45019, 43025]
Precisions  ['58.71', '33.94', '21.38', '13.77']  ['58.71', '33.95', '21.38', '13.77']  ['58.71', '33.95', '21.38', '13.77']  ['58.71', '33.95', '21.38', '13.77']  ['58.45', '33.86', '21.51', '13.94']
Bp          0.9906605085002174                    0.9906192638444444                    0.9906192638444444                    0.9906192638444444                    1.0
Sys_len     48490                                 48488                                 48488                                 48488                                 49015
ref_len     48945                                 48945                                 48945                                 48945                                 48945
==========  ====================================  ====================================  ====================================  ====================================  ====================================

**Comment by hasuoshenyun** [comment]
![tmp](https://github.com/teelinsan/parallel-decoding/assets/16149291/50e95281-9e1b-47b5-b48c-99853906c4b5)

**Comment by teelinsan** [comment]
Hi @hasuoshenyun,
I can see that you are not using the same eval setup proposed in the paper. To appreciate the time speedup you should be sure that all the algorithms are running in parallel. This is a known limitation, I report what we wrote in the Limitation section of the paper: "[...] to appreciate the speedup one should be able to run computations in parallel. Using parallel decoding without parallel resources or parallel-optimized software may increase wall-clock time due to overheads, leading to a waste of computation. This is further discussed in Section 4.3 "Computational Scaling". The reported wall-clock time results are thus to be considered within the scope of the experimental setup proposed in this paper and they may vary depending on the underlying hardware and software."
The best way to reproduce the results is to use cloud resources to setup the machines following the instructions in the readme. On other hardware, you have to check that your operations are running in parallel.
